# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Deploy Frontend to AWS EC2

# Gatilho: Este workflow roda sempre que houver um push na branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # Primeiro Job: Buildar a imagem Docker e enviar para o Docker Hub
  build-and-push:
    runs-on: ubuntu-latest # O trabalho será executado em uma máquina virtual Ubuntu
    
    steps:
      # 1. Clona o seu repositório para a máquina virtual do Actions
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Faz o login no Docker Hub usando os secrets que configuramos
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Builda a imagem Docker a partir do seu Dockerfile e envia para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: matteusmoreno/casa-moreno-frontend:latest # O nome da sua imagem no Docker Hub

  # Segundo Job: Fazer o deploy na EC2
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Garante que este job só rode se o 'build-and-push' for bem-sucedido
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master # Ação popular para executar comandos via SSH
        with:
          host: ${{ secrets.AWS_EC2_HOST }} # Pega o host da EC2 dos secrets
          username: ${{ secrets.AWS_EC2_USER }} # Pega o usuário da EC2 dos secrets
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }} # Pega a chave SSH dos secrets
          script: |
            # 1. Baixa a imagem mais recente do Docker Hub
            docker pull matteusmoreno/casa-moreno-frontend:latest
            
            # 2. Para o container atual, se ele estiver rodando
            docker stop casa-moreno-frontend-container || true
            
            # 3. Remove o container antigo
            docker rm casa-moreno-frontend-container || true
            
            # 4. Inicia um novo container com a imagem atualizada
            docker run --name casa-moreno-frontend-container -d -p 3001:3001 --restart always matteusmoreno/casa-moreno-frontend:latest
